version: '2'
services:
  sdk:
    build:
      context: .
      dockerfile: sdk.Dockerfile
    env_file:
      - ./sdk.env
    volumes:
      - ./scripts:/app/scripts
      - ./settings:/app/settings
      - ./sonar-report:/app/sonar-report
      - ./src:/app/src
      - ./test:/app/test
      - ./test-report:/app/test-report