version: '3.7'

services:
  dev:
    build:
      context: app
      target: dev
      args:
        PROJECT_PATH: ${PROJECT_PATH}
    env_file:
      - ./app/env/web.env
      - ./app/env/web.dev.env
    environment:
      - "PROJECT_FOLDER_PATH=${PROJECT_FOLDER_PATH}"
      - "DLL_NAME=${DLL_NAME}"
    image: "${WEB_IMAGE_NAME}-dev:${VERSION}"
    volumes:
      - ./app/CleanSolution.sln:/app/CleanSolution.sln
      - ./app/Makefile:/app/Makefile
      - ./app/scripts:/app/scripts
      - ./app/settings:/app/settings
      - ./app/sonar-report:/app/sonar-report
      - ./app/src:/app/src
      - ./app/test:/app/test
      - ./app/test-report:/app/test-report
      - ./app/behavioral-test-results:/app/behavioral-test-results
      - ./app/swagger-output:/app/swagger-output
    command: "echo 'shutting down'"
  prod:
    build:
      context: app
      target: prod
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        DLL_NAME: ${DLL_NAME}
    image: "${WEB_IMAGE_NAME}-prod:${VERSION}"
    command: "echo 'shutting down'"
  web:
    container_name: web
    domainname: app
    image: "${WEB_IMAGE_NAME}-${WEB_ENV}:${VERSION}"
    env_file:
      - ./app/env/web.env
      - ./app/env/web.dev.env
    volumes:
      - ./app/CleanSolution.sln:/app/CleanSolution.sln
      - ./app/Makefile:/app/Makefile
      - ./app/scripts:/app/scripts
      - ./app/settings:/app/settings
      - ./app/sonar-report:/app/sonar-report
      - ./app/src:/app/src
      - ./app/test:/app/test
      - ./app/test-report:/app/test-report
      - ./app/behavioral-test-results:/app/behavioral-test-results
    ports:
      - 8000:80
    healthcheck:
      test: curl --fail http://localhost/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - wiremock
      - sqlserver
      - queues
      - dev
      - prod
  wiremock:
    domainname: app
    container_name: wiremock
    build:
      context: wiremock
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/files:/home/wiremock/__files
  sqlserver:
    domainname: app
    container_name: sqlserver
    build:
      context: sqlserver
    ports:
      - 9002:1433
    environment:
      SA_PASSWORD: "@_str0nG-p@ssw0rd!"
      ACCEPT_EULA: "Y"
  queues:
    build:
      context: queue
    ports:
      - 9004:10000
      - 9005:10001
    command: "azurite-queue --loose --queueHost 0.0.0.0"