version: '3.7'

services:
  web:
    depends_on:
      - sonarqube
    environment:
      - "SONAR_PROJECT_KEY=product-service"
      - "SONAR_PROJECT_NAME=ProductService"
      - "SONAR_LOGIN=admin"
      - "SONAR_PASSWORD=admin"
      - "SONAR_URI=http://sonarqube:9000"
    command: "tail /dev/null -f"
    healthcheck:
      test: exit 0
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  sonarqube:
    domainname: app
    container_name: sonarqube
    build:
      context: sonarqube
    ports:
      - 9000:9000
    environment:
      - "SONAR_LOGIN=admin"
      - "SONAR_PASSWORD=admin"
      - "SONAR_URI=http://127.0.0.1:9000"
    volumes:
      - ./sonarqube/sonar-conf:/opt/sonarqube/conf
      - ./sonarqube/scripts:/scripts
    healthcheck:
      test: /bin/bash /scripts/healthcheck.sh
      interval: 20s
      retries: 30
      start_period: 20s
      timeout: 10s