version: '3.7'
services:
  web:
    depends_on:
      - sonarqube
    environment:
      - "SONAR_PROJECT_KEY=product-service"
      - "SONAR_PROJECT_NAME=ProductService"
      - "SONAR_LOGIN=admin"
      - "SONAR_PASSWORD=admin"
      - "SONAR_URI=http://sonarqube:9000"
    command: "tail /dev/null -f"
  sonarqube:
    domainname: app
    container_name: sonarqube
    build:
      context: sonarqube
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/sonar-conf:/opt/sonarqube/conf