version: 2.1

defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:buster-scm

commands:
  docker_login_command:
    steps:
      - run:
          name: Docker login
          command: |
            echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_LOGIN}" --password-stdin
  build_sdk_command:
    steps:
      - run:
          name: Build SDK container
          command: |
            docker-compose -f docker-compose.sdk.yml build sdk
      - run:
          name: List SDK current working directory
          command: |
            docker-compose -f docker-compose.sdk.yml run sdk ls
      - run:
          name: Echo SDK current working directory
          command: |
            docker-compose -f docker-compose.sdk.yml run sdk bash -c "echo $PWD"
  unit_tests_command:
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - build_sdk_command
      - run:
          name: Run Unit Tests
          command: |
            make unit_test
  behavioral_tests_command:
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Show current directory
          command: |
            ls
      - run:
          name: Run Behavioral Tests
          command: |
            make behavioral_test

  sonar_scan_command:
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Show current directory
          command: |
            ls
      - run:
          name: Run Sonarqube Scan
          command: |
            make run_sonar_scan
            
jobs:
  unit_tests:
    <<: *defaults
    steps:
      - docker_login_command
      - unit_tests_command
  behavioral_tests:
    <<: *defaults
    steps:
      - docker_login_command
      - behavioral_tests_command
  sonar_scan:
    <<: *defaults
    steps:
      - docker_login_command
      - sonar_scan_command

workflows:
  default:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /.*/