version: 2.1

defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:buster-scm

commands:
  unit_tests_command:
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: |
            ls
  
jobs:
  unit_tests:
    <<: *defaults
    steps:
      - unit_tests_command

workflows:
  default:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /.*/
