version: 2.1

defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:buster-scm

commands:
  docker_login_command:
    steps:
      - run:
          name: Docker login
          command: |
            echo ${DOCKER_PASSWORD} | docker login -u "${DOCKER_LOGIN}" --password-stdin
  unit_tests_command:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: |
            docker -v
      - run:
          name: Run Unit Tests
          command: |
            docker-compose -v
      - run:
          name: Run Unit Tests
          command: |
            make unit_test
jobs:
  unit_tests:
    <<: *defaults
    steps:
      - docker_login_command
      - unit_tests_command

workflows:
  default:
    jobs:
      - unit_tests:
          filters:
            tags:
              only: /.*/
