version: '3.7'
services:
  wiremock:
    domainname: app
    container_name: wiremock
    image: rodolpheche/wiremock
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ../../wiremock/mappings:/home/wiremock/mappings
      - ../../wiremock/files:/home/wiremock/__files
