version: '3.7'
services:
  sonarqube:
    domainname: app
    container_name: sonarqube
    image: sonarqube:8.2-community
    ports:
      - 9000:9000
    volumes:
      - ../../sonar-conf:/opt/sonarqube/conf