version: '2'
services:
  mongodb:
    domainname: app
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ../../docker/mongo/mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=product-service