name: Build and Test

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Install make
        run: sudo apt-get install -y make
        
      - name: Build and tag
        run: make build_and_tag
        
      - name: Start sonar scan
        run: make start_sonar_scan_ci
        
      - name: Run unit tests
        run: make run_unit_tests_ci
        
      - name: Run functional tests
        run: make run_functional_tests_ci

      - name: End sonar scan
        run: make end_sonar_scan_ci
        if: ${{ always() }}
        
      - name: Generate sonar report
        run: make generate_sonar_report
        
      - name: Shut containers down
        run: make shut_containers_down_ci