name: Build and Test

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Install make
        run: sudo apt-get install -y make
        
      - name: Use docker layer caching  
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Build and tag
        run: make build_and_tag save_all_images docker_username=${{ secrets.DOCKER_USERNAME }} version=alpha-${{github.run_number}}
        
      - name: Run unit tests
        run: make load_all_images run_unit_tests_dev docker_username=${{ secrets.DOCKER_USERNAME }} version=alpha-${{github.run_number}}
        
      - name: Upload unit tests artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/test-report
        if: ${{ always() }}
        
      - name: Run functional tests
        run: make load_all_images run_functional_tests_dev docker_username=${{ secrets.DOCKER_USERNAME }} version=alpha-${{github.run_number}}
        
      - name: Upload functional tests artifact
        uses: actions/upload-artifact@v3
        with:
          name: behavioral-test-results
          path: app/behavioral-test-results
        if: ${{ always() }}
        
      - name: Generate swagger
        run: make load_all_images generate_swagger

      - name: Upload swagger artifact
        uses: actions/upload-artifact@v3
        with:
          name: swagger
          path: app/swagger-output/swagger.yaml
        if: ${{ always() }}  

      - name: Shut containers down
        run: make shut_containers_down_ci docker_username=${{ secrets.DOCKER_USERNAME }} version=alpha-${{github.run_number}}
        
      - name: Push images to artifactory repository
        run: make load_all_images push_images docker_username=${{ secrets.DOCKER_USERNAME }} version=alpha-${{github.run_number}}